### ISSUE TITLE
Missing dependency on ros-noetic-controller-manager-msgs

### ISSUE THREAD

**Issue by alexdewar** [ros-noetic-arch/ros-noetic-diff-drive-controller#3]
Without ros-noetic-controller-manager-msgs, this package fails to build. I'm not sure if this is just a build dependency or not.

**Comment by acxz** [comment]
Just tried building without `ros-noetic-controller-manager-msgs` and looks like your right. I guess I never ran into this issue because I had it installed as a make dep from a previous package during the installation pipeline.

**Comment by acxz** [comment]
I have made an upstream issue and patched it locally (e13199b) for the Arch package. Closing this issue.
